### ISSUE TITLE
Change the name to epikit

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/msfmisc#1]
n.b. epimisc is technically already taken.

Since this is a more general-use package inline stuff and other things, it's not _necessarily_ epi-related.

**Comment by aspina7** [comment]
true - how about statline?

**Comment by zkamvar** [comment]
> true - how about statline?

Implies that it actually does statistics

**Comment by aspina7** [comment]
how about not statline?

**Comment by zkamvar** [comment]
oooo epikit

**Comment by aspina7** [comment]
Awesome!
