### ISSUE TITLE
separator argument in unite_ci()

### ISSUE THREAD

**Issue by pavilaalo** [R4EPI/msfmisc#27]
Hello,

Would it be possible to add a "separator" argument to the unite_ci() function to be able to modify the default "--" between values?

It is sometimes changed to "to" or just "-"
Appreciate it.

**Comment by aspina7** [comment]
hello - thanks for this, yes it is something we need to add for sure, just not sure on the timeline for when we can get this done just yet. Will keep you posted once it gets moving!

**Comment by pavilaalo** [comment]
Great, thanks a lot!

**Comment by aspina7** [comment]
@pavilaalo this is updated - if you install from github you should be able to use this.... might be a while yet before on CRAN though.

**Comment by pavilaalo** [comment]
Excellent, thank you so much. Appreciate it
